export { writeEnvSecrets, secretsPresent, REPO_ROOT, readConfig, keySource } from "./env.ts";
export type { JarheadConfig } from "./env.ts";
export { newId } from "./ids.ts";
export { LineSplitter } from "./ndjson.ts";
export { logger, setLogLevel, addLogSink, replaceDefaultSink } from "./log.ts";
export type { Logger, LogLevel } from "./log.ts";
export { Marks } from "./marks.ts";
export { Ledger } from "./ledger.ts";
export { Trash } from "./trash.ts";
export type { SweepResult } from "./trash.ts";
export { classifyAction, classifyPath, classifyAppleScript, classifyUrl, riskyUrlReason, expandPath, namedPaths, secretPathReason, secretEnvReason, shellCwdReason, isLoopbackHost, isPrivateHost, HANDS_OFF_APPS, grantClassOf, presenceGated, presenceReason, PRESENCE_WINDOW_MS, PRESENCE_ABSENT, TRASH_REASON } from "./policy.ts";
export type { ActionContext, Decision, Presence, Verdict } from "./policy.ts";
export { classifyAutomation, triggerReason, actionReason, costLine, shellSteals, openPathReason, AUTOMATION_RESERVED_TRIGGERS, BACKGROUND_SHELL_REFUSE, OPEN_BACKGROUND_FLAG, OPEN_EXECUTABLE_EXT } from "./policy.ts";
export type { AutomationContext } from "./policy.ts";
export { parseWhen, nextFire, describe, describeEvent, describeInstant, inQuiet, quietEnds, inWindow, graceFor, snoozeDefault, clockOf, weekdayOf, atClock, WEEKDAYS, PARSE_LEAD_MS, INTERVAL_MIN_MS } from "./schedule.ts";
export type { ParsedWhen } from "./schedule.ts";
export { dataPaths } from "./privacy.ts";
export type { DataPathsInput } from "./privacy.ts";
