import { readdir, stat } from "node:fs/promises";
import { homedir } from "node:os";
import { basename, join } from "node:path";
import {
  DEFAULT_LIMIT,
  DEFAULT_MAX_AGE_DAYS,
  MAX_ASSISTANT_CHARS,
  ParseCache,
  extrapolateCount,
  isRecord,
  newestFirst,
  parseJsonLine,
  parseTimestamp,
  readHeadTail,
  str,
  stripTags,
  truncate,
  type DiscoveredSession,
  type StoreOptions,
} from "./store.ts";

/**
 * Claude Code's own session store: ~/.claude/projects/<slug>/<sessionId>.jsonl.
 *
 * Line shapes seen on this machine (Claude Code 2.1.x):
 *   {"type":"user","message":{"role":"user","content":"..."|[blocks]},"timestamp","cwd","sessionId","isSidechain"}
 *   {"type":"assistant","message":{"model","id":"msg_…","type":"message","role":"assistant","content":[one block]},...}
 *     — one line per content block: a message with thinking, text and two tool_use blocks is
 *       four consecutive lines sharing `message.id`, so messages are counted per id, not per line
 *   {"type":"summary","summary":"..."}           older continued sessions
 *   {"type":"custom-title","customTitle":"..."}  set by Kevin
 *   {"type":"ai-title","aiTitle":"..."}          generated by Claude Code
 *   {"type":"queue-operation"|"system"|"last-prompt"|"pr-link"|"attachment"|...}
 * Subagent transcripts live in <sessionId>/subagents/ and are not sessions.
 *
 * User lines are not all Kevin. The harness injects whole blocks into them — Claude
 * Desktop's `<system-reminder>` scratch-workspace preamble ahead of the first real
 * prompt, `<local-command-caveat>`/`<local-command-stdout>` around slash commands that
 * ran locally, `<task-notification>` for finished background tasks — and marks some
 * lines `"isMeta":true`. userText() drops all of that and keeps what he typed.
 */

const HEAD_BYTES = 64 * 1024;
const TAIL_BYTES = 256 * 1024;
const SESSION_FILE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.jsonl$/i;
const TIMESTAMP_RE = /"timestamp":"([^"]+)"/;
const CWD_RE = /"cwd":"((?:[^"\\]|\\.)*)"/;
const TITLE_LINE = /^\{"type":"(custom-title|ai-title|summary)"/;
/**
 * `message.id` of an assistant line without a JSON.parse: the id sits among the scalar
 * keys ahead of `content`, and `[^[\]]` keeps the match from wandering into the content
 * array (whose tool_use blocks carry ids of their own).
 */
const MESSAGE_ID_RE = /"message":\{[^[\]]*?"id":"([^"]+)"/;

export function defaultClaudeProjectsRoot(home = homedir()): string {
  return join(home, ".claude", "projects");
}

/**
 * "-Users-kevinliu-gt-gt-cloud" → "/Users/kevinliu/gt/gt-cloud". Dashes inside a
 * segment are indistinguishable from separators, so callers prefer the in-file cwd.
 */
export function decodeProjectSlug(slug: string): string {
  if (!slug.startsWith("-")) return slug;
  return slug.replace(/-/g, "/");
}

interface Candidate {
  readonly path: string;
  readonly slug: string;
  readonly mtimeMs: number;
  readonly size: number;
}

export class ClaudeStore {
  readonly root: string;
  private readonly maxAgeDays: number;
  private readonly limit: number;
  private readonly now: () => number;
  private readonly cache = new ParseCache<DiscoveredSession>();

  constructor(opts: StoreOptions & { readonly root?: string } = {}) {
    this.root = opts.root ?? defaultClaudeProjectsRoot();
    this.maxAgeDays = opts.maxAgeDays ?? DEFAULT_MAX_AGE_DAYS;
    this.limit = opts.limit ?? DEFAULT_LIMIT;
    this.now = opts.now ?? Date.now;
  }

  async exists(): Promise<boolean> {
    try {
      return (await stat(this.root)).isDirectory();
    } catch {
      return false;
    }
  }

  /** Newest sessions within the age window, capped, parsed from head+tail. */
  async scan(): Promise<DiscoveredSession[]> {
    const candidates = newestFirst(await this.candidates(), this.limit);
    const sessions = await Promise.all(candidates.map((c) => this.load(c)));
    this.cache.retain(new Set(candidates.map((c) => c.path)));
    return sessions.filter((s): s is DiscoveredSession => s !== undefined);
  }

  /** Parse one session by id regardless of age/cap; undefined when not on disk. */
  async find(sessionId: string): Promise<DiscoveredSession | undefined> {
    const all = await this.candidates(true);
    const c = all.find((x) => basename(x.path, ".jsonl") === sessionId);
    return c ? this.load(c) : undefined;
  }

  private async candidates(ignoreAge = false): Promise<Candidate[]> {
    let slugs: string[];
    try {
      slugs = (await readdir(this.root, { withFileTypes: true })).filter((d) => d.isDirectory()).map((d) => d.name);
    } catch {
      return [];
    }
    const cutoff = ignoreAge ? -Infinity : this.now() - this.maxAgeDays * 86_400_000;
    const perSlug = await Promise.all(
      slugs.map(async (slug): Promise<Candidate[]> => {
        const dir = join(this.root, slug);
        let names: string[];
        try {
          names = (await readdir(dir)).filter((n) => SESSION_FILE.test(n));
        } catch {
          return [];
        }
        const stats = await Promise.all(
          names.map(async (n) => {
            const path = join(dir, n);
            try {
              const st = await stat(path);
              return st.isFile() && st.mtimeMs >= cutoff ? { path, slug, mtimeMs: st.mtimeMs, size: st.size } : undefined;
            } catch {
              return undefined;
            }
          }),
        );
        return stats.filter((c): c is Candidate => c !== undefined);
      }),
    );
    return perSlug.flat();
  }

  private async load(c: Candidate): Promise<DiscoveredSession | undefined> {
    const cached = this.cache.get(c.path, c.mtimeMs, c.size);
    if (cached) return cached;
    try {
      const slices = await readHeadTail(c.path, HEAD_BYTES, TAIL_BYTES);
      const parsed = parseClaudeSession(basename(c.path, ".jsonl"), c.path, c.slug, slices.head, slices.tail, {
        whole: slices.whole,
        bytesRead: slices.bytesRead,
        size: slices.size,
        mtimeMs: slices.mtimeMs,
      });
      this.cache.set(c.path, slices.mtimeMs, slices.size, parsed);
      return parsed;
    } catch {
      return undefined;
    }
  }
}

interface FileFacts {
  readonly whole: boolean;
  readonly bytesRead: number;
  readonly size: number;
  readonly mtimeMs: number;
}

/** Pure: build a DiscoveredSession from the head and tail lines of one file. */
export function parseClaudeSession(sessionId: string, path: string, slug: string, head: readonly string[], tail: readonly string[], file: FileFacts): DiscoveredSession {
  let cwd: string | undefined;
  let customTitle: string | undefined;
  let aiTitle: string | undefined;
  let summary: string | undefined;
  let firstPrompt: string | undefined;
  let lastAssistantText: string | undefined;
  let startedAt: number | undefined;
  let lastTimestamp: number | undefined;
  let messages = 0;
  /** `message.id` of the previous assistant line; the lines of one message are consecutive. */
  let lastAssistantId: string | undefined;

  // Most bytes are tool results and tool calls, which only need counting. Cheap
  // substring checks decide whether a line is worth a JSON.parse at all.
  const visit = (line: string): void => {
    const ts = parseTimestamp(TIMESTAMP_RE.exec(line)?.[1]);
    if (ts !== undefined) {
      startedAt = startedAt === undefined ? ts : Math.min(startedAt, ts);
      lastTimestamp = lastTimestamp === undefined ? ts : Math.max(lastTimestamp, ts);
    }
    if (cwd === undefined) cwd = CWD_RE.exec(line)?.[1];
    if (line.includes('"type":"assistant"')) {
      if (line.includes('"isSidechain":true')) return;
      // A line without an id (older builds, hand-made fixtures) is a message of its own.
      const messageId = MESSAGE_ID_RE.exec(line)?.[1];
      if (messageId === undefined || messageId !== lastAssistantId) messages += 1;
      lastAssistantId = messageId;
      if (!line.includes('"type":"text"')) return;
    } else if (line.includes('"type":"user"')) {
      if (line.includes('"isSidechain":true') || line.includes('"isMeta":true') || line.includes('"tool_result"')) return;
    } else if (!TITLE_LINE.test(line)) {
      return;
    }
    const o = parseJsonLine(line);
    if (!o) return;
    const type = str(o["type"]);
    switch (type) {
      case "custom-title":
        customTitle = str(o["customTitle"]) ?? customTitle;
        return;
      case "ai-title":
        aiTitle = str(o["aiTitle"]) ?? aiTitle;
        return;
      case "summary":
        summary = str(o["summary"]) ?? summary;
        return;
      case "user": {
        if (o["isSidechain"] === true || o["isMeta"] === true) return;
        const text = userText(o["message"]);
        if (text === undefined) return;
        messages += 1;
        firstPrompt ??= text;
        return;
      }
      case "assistant": {
        if (o["isSidechain"] === true) return;
        const text = assistantText(o["message"]);
        if (text) lastAssistantText = text;
        return;
      }
      default:
        return;
    }
  };

  for (const line of head) visit(line);
  for (const line of tail) visit(line);

  const title = customTitle ?? aiTitle ?? summary;
  return {
    tool: "claude",
    id: sessionId,
    source: "user",
    parentId: undefined,
    path,
    cwd: cwd ?? decodeProjectSlug(slug),
    title: title ? truncate(title, 80) : undefined,
    firstPrompt: firstPrompt ? truncate(firstPrompt, 80) : undefined,
    lastAssistantText: lastAssistantText ? lastAssistantText.slice(0, MAX_ASSISTANT_CHARS) : undefined,
    startedAt,
    lastActivityAt: Math.max(file.mtimeMs, lastTimestamp ?? 0),
    mtimeMs: file.mtimeMs,
    sizeBytes: file.size,
    messageCount: file.whole ? messages : extrapolateCount(messages, file.bytesRead, file.size),
    messageCountExact: file.whole,
    archived: false,
  };
}

/**
 * Whole blocks the harness writes into user turns. None of it is Kevin's text, so the
 * block goes, body included. `<command-name>`/`<command-args>` are handled apart: the
 * slash command and its arguments are what he typed.
 */
const HARNESS_BLOCK =
  /<(system-reminder|local-command-caveat|local-command-stdout|local-command-stderr|command-message|skill-format|task-notification|user-memory-input|ide_[a-z_]+|bash-stdout|bash-stderr)>[\s\S]*?<\/\1>/gi;
/** A block that opens but never closes (cut by the head budget) is all harness too. */
const HARNESS_OPEN = /^\s*<(system-reminder|local-command-caveat|local-command-stdout|local-command-stderr|command-message|task-notification)[\s>]/i;
const COMMAND_NAME = /<command-name>([\s\S]*?)<\/command-name>/i;
const COMMAND_ARGS = /<command-args>([\s\S]*?)<\/command-args>/i;

/**
 * Human-typed text of a user line; undefined for tool results, interrupts, attachments
 * and lines that are harness through and through. Exported for tests.
 */
export function userText(message: unknown): string | undefined {
  if (!isRecord(message)) return undefined;
  const content = message["content"];
  let text: string | undefined;
  if (typeof content === "string") text = content;
  else if (Array.isArray(content)) {
    const parts: string[] = [];
    for (const block of content) {
      if (!isRecord(block)) continue;
      if (block["type"] === "tool_result") return undefined;
      if (block["type"] === "text" && typeof block["text"] === "string") parts.push(block["text"]);
    }
    text = parts.join("\n");
  }
  if (text === undefined) return undefined;
  let body = text.replace(HARNESS_BLOCK, " ");
  if (HARNESS_OPEN.test(body)) return undefined;
  const command = COMMAND_NAME.exec(body)?.[1]?.trim();
  if (command !== undefined) {
    // "/review PR 12" is his; a bare "/clear" or "/compact" is housekeeping, not a prompt.
    const args = COMMAND_ARGS.exec(body)?.[1]?.trim();
    if (!args) return undefined;
    body = `${command} ${args}`;
  }
  const clean = stripTags(body);
  if (!clean || /^\[Request interrupted/i.test(clean)) return undefined;
  return clean;
}

function assistantText(message: unknown): string | undefined {
  if (!isRecord(message)) return undefined;
  const content = message["content"];
  if (typeof content === "string") return content.trim() || undefined;
  if (!Array.isArray(content)) return undefined;
  const parts: string[] = [];
  for (const block of content) {
    if (isRecord(block) && block["type"] === "text" && typeof block["text"] === "string") parts.push(block["text"]);
  }
  const text = parts.join("\n").trim();
  return text || undefined;
}
